### ISSUE TITLE
Two mouse disambiguation errors

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1141]
This process has worked for nearly every one of my samples, but there are two issues that have arisen with a handful of samples.

```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 209, in run
    samples = run_parallel("process_alignment", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 38, in process_alignment
    return sample.process_alignment(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 113, in process_alignment
    bam.check_header(out_bam, data["rgnames"], data["sam_ref"], data["config"])
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 128, in check_header
    _check_bam_contigs(in_bam, ref_file, config)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 172, in _check_bam_contigs
    % "\n".join(problems))
ValueError: Unexpected order, name or contig mismatches between input BAM and reference file:
Reference mismatch. BAM: 1 Reference: chr1
Reference mismatch. BAM: 2 Reference: chr2
Reference mismatch. BAM: 3 Reference: chr3
Reference mismatch. BAM: 4 Reference: chr4
Reference mismatch. BAM: 5 Reference: chr5
Reference mismatch. BAM: 6 Reference: chr6
Reference mismatch. BAM: 7 Reference: chr7
Reference mismatch. BAM: 8 Reference: chr8
Reference mismatch. BAM: 9 Reference: chr9
Reference mismatch. BAM: 10 Reference: chr10
Reference mismatch. BAM: 11 Reference: chr11
Reference mismatch. BAM: 12 Reference: chr12
Reference mismatch. BAM: 13 Reference: chr13
Reference mismatch. BAM: 14 Reference: chr14
Reference mismatch. BAM: 15 Reference: chr15
Reference mismatch. BAM: 16 Reference: chr16
Reference mismatch. BAM: 17 Reference: chr17
Reference mismatch. BAM: 18 Reference: chr18
Reference mismatch. BAM: 19 Reference: chr19
Reference mismatch. BAM: 20 Reference: chrX
Reference mismatch. BAM: 21 Reference: chrY
Reference mismatch. BAM: 22 Reference: chrM
Reference mismatch. BAM: X Reference: chr1_GL456210_random
Reference mismatch. BAM: Y Reference: chr1_GL456211_random
Reference mismatch. BAM: MT Reference: chr1_GL456212_random
Reference mismatch. BAM: GL000207.1 Reference: chr1_GL456213_random
Reference mismatch. BAM: GL000226.1 Reference: chr1_GL456221_random
Reference mismatch. BAM: GL000229.1 Reference: chr4_GL456216_random
Reference mismatch. BAM: GL000231.1 Reference: chr4_GL456350_random
Reference mismatch. BAM: GL000210.1 Reference: chr4_JH584292_random
Reference mismatch. BAM: GL000239.1 Reference: chr4_JH584293_random
Reference mismatch. BAM: GL000235.1 Reference: chr4_JH584294_random
Reference mismatch. BAM: GL000201.1 Reference: chr4_JH584295_random
Reference mismatch. BAM: GL000247.1 Reference: chr5_GL456354_random
Reference mismatch. BAM: GL000245.1 Reference: chr5_JH584296_random
Reference mismatch. BAM: GL000197.1 Reference: chr5_JH584297_random
Reference mismatch. BAM: GL000203.1 Reference: chr5_JH584298_random
Reference mismatch. BAM: GL000246.1 Reference: chr5_JH584299_random
Reference mismatch. BAM: GL000249.1 Reference: chr7_GL456219_random
Reference mismatch. BAM: GL000196.1 Reference: chrX_GL456233_random
Reference mismatch. BAM: GL000248.1 Reference: chrY_JH584300_random
Reference mismatch. BAM: GL000244.1 Reference: chrY_JH584301_random
Reference mismatch. BAM: GL000238.1 Reference: chrY_JH584302_random
Reference mismatch. BAM: GL000202.1 Reference: chrY_JH584303_random
Reference mismatch. BAM: GL000234.1 Reference: chrUn_GL456239
Reference mismatch. BAM: GL000232.1 Reference: chrUn_GL456359
Reference mismatch. BAM: GL000206.1 Reference: chrUn_GL456360
Reference mismatch. BAM: GL000240.1 Reference: chrUn_GL456366
Reference mismatch. BAM: GL000236.1 Reference: chrUn_GL456367
Reference mismatch. BAM: GL000241.1 Reference: chrUn_GL456368
Reference mismatch. BAM: GL000243.1 Reference: chrUn_GL456370
Reference mismatch. BAM: GL000242.1 Reference: chrUn_GL456372
Reference mismatch. BAM: GL000230.1 Reference: chrUn_GL456378
Reference mismatch. BAM: GL000237.1 Reference: chrUn_GL456379
Reference mismatch. BAM: GL000233.1 Reference: chrUn_GL456381
Reference mismatch. BAM: GL000204.1 Reference: chrUn_GL456382
Reference mismatch. BAM: GL000198.1 Reference: chrUn_GL456383
Reference mismatch. BAM: GL000208.1 Reference: chrUn_GL456385
Reference mismatch. BAM: GL000191.1 Reference: chrUn_GL456387
Reference mismatch. BAM: GL000227.1 Reference: chrUn_GL456389
Reference mismatch. BAM: GL000228.1 Reference: chrUn_GL456390
Reference mismatch. BAM: GL000214.1 Reference: chrUn_GL456392
Reference mismatch. BAM: GL000221.1 Reference: chrUn_GL456393
Reference mismatch. BAM: GL000209.1 Reference: chrUn_GL456394
Reference mismatch. BAM: GL000218.1 Reference: chrUn_GL456396
Reference mismatch. BAM: GL000220.1 Reference: chrUn_JH584304
Setting `bam_clean: picard` in the configuration can often fix this issue.
```

With the samples that receive this error, they are from a pre-aligned bam. They are aligned with the reference file that comes with GATK bundle. I am not sure if that would cause some sort of issue, but I believe I have had bcbio gernally work for bams aligned with that reference files before. Regardless, it is saying mismatchs with the prefix 'chr' which from my understanding is not GRCh37 format. Some of that might be the general multiprocessing errors when things break. Maybe I should try in single core mode, but it is not clear to me what the problem is.

**Comment by bwubb** [comment]
Second issue happened in maybe three samples.

```
[2015-12-04T20:56Z] Index BAM file: 1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-X_41196610_155270560-prep.bam
[2015-12-04T20:56Z] Select unmapped reads
[2015-12-04T20:56Z] Index BAM file: 1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-nochrom-prep.bam
[2015-12-04T20:56Z] Select unanalyzed reads
[2015-12-04T20:57Z] Index BAM file: 1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-noanalysis-prep.bam
[2015-12-04T20:57Z] Timing: variant calling
[2015-12-04T20:57Z] multiprocessing: variantcall_sample
[2015-12-04T20:57Z] Genotyping with VarDict: Inference
[2015-12-04T20:57Z] Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
[2015-12-04T20:57Z]   line 1 did not have 34 elements
[2015-12-04T20:57Z] Calls: read.table -> scan
[2015-12-04T20:57Z] Execution halted
[2015-12-04T20:57Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC -Djava.io.tmpdir=/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/tx/tmpKZI1nU' && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#4p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/bamprep/1205PRT#4p2+/1/1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22385180-prep.bam -c 1 -S 2 -E 3 -g 4 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/1205PRT#4p2+-1_0_22385180-raw-unmerged-regions-regionlimit.bed | teststrandbias.R| var2vcf_valid.pl -N 1205PRT#4p2+ -E -f 0.1  | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /home/bwubb/bcbio-tools/bin/vcfstreamsort | bgzip -c > /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/tx/tmpKZI1nU/1205PRT#4p2+-1_0_22385180-raw.vcf.gz
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 1 did not have 34 elements
Calls: read.table -> scan
Execution halted
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 229, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 138, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 252, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 78, in run_vardict
    assoc_files, region, out_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 245, in _run_vardict_paired
    assoc_files, region, out_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 148, in _run_vardict_caller
    do.run(cmd.format(**locals()), "Genotyping with VarDict: Inference", {})
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC -Djava.io.tmpdir=/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/tx/tmpKZI1nU' && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#4p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/bamprep/1205PRT#4p2+/1/1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22385180-prep.bam -c 1 -S 2 -E 3 -g 4 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/1205PRT#4p2+-1_0_22385180-raw-unmerged-regions-regionlimit.bed | teststrandbias.R| var2vcf_valid.pl -N 1205PRT#4p2+ -E -f 0.1  | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /home/bwubb/bcbio-tools/bin/vcfstreamsort | bgzip -c > /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/tx/tmpKZI1nU/1205PRT#4p2+-1_0_22385180-raw.vcf.gz
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 1 did not have 34 elements
Calls: read.table -> scan
Execution halted
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Brad;
Sorry about the problems. The first issue is due to a mismatch between your pre-aligned BAM and the reference genome you selected. It looks like the BAM was aligned against GRCh37 (1, 2, 3..) and the reference genome is hg19 (chr1, chr2, chr3...). You either need to select compatible genomes, or realign the inputs with bcbio to avoid the problem.

For the second issue, it looks like vardict is failing on some of the samples, so the post-processing R script is complaining about empty inputs. It's a bit hard to debug this remotely but happy to help more if you could reproduce with the failing command line and make the BAM file available:
```
unset R_HOME && export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#4p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/bamprep/1205PRT#4p2+/1/1205PRT#4p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22385180-prep.bam -c 1 -S 2 -E 3 -g 4 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#4p2+/work/vardict/1/1205PRT#4p2+-1_0_22385180-raw-unmerged-regions-regionlimit.bed | teststrandbias.R | var2vcf_valid.pl -N 1205PRT#4p2+ -E -f 0.1 > test.vcf
```
If you're running an older version of vardict-java it also might be worth doing a `bcbio_nextgen.py upgrade --tools` as there have been a couple of fixes recently for edge cases. Hope this helps.

**Comment by bwubb** [comment]
Thanks. I will try the tools upgrade first then see about generating the command line error. The fist issue seems very odd to me. I have never used an hg19 fasta ever. The yaml specifies GRCh37 with an mm10 disambiguation. While the GrCh37 fasta I use is slightly different from the one provided with bcbio, the main chromosome numbering and order is the same. I guess the best thing to do would be to re-align with bcbio provided GRCh37 fasta and see if that fixes the issue. Thanks.

**Comment by chapmanb** [comment]
Brad;
Thanks for checking the issue. Apologies, despite the title of this issue it totally escaped my mind that you were doing disambiguation when replying. You definitely need to realign with disambiguation since it needs to perform alignment against both the original GRCh37 and mm10, then use this to make the determination about what aligns better to human. It's probably getting confused without alignment and starting to assess the mm10 genome. Hopefully doing alignment fixes that issue. Thanks again.

**Comment by bwubb** [comment]
Ok I need to make sure I am executing this correctly. The posted command was missing a closing single quote, which I placed before the first pipe operator. However the test.vcf was empty except for the header lines.

Which bam file do your require, the *-prep.bam in the command? And what is the best way to make that available for you?

**Comment by bwubb** [comment]
> You definitely need to realign with disambiguation since it needs to perform alignment against both the original GRCh37 and mm10, then use this to make the determination about what aligns better to human.

Can you clarify that more? I changed my prealignment reference to the GRCh37.fa included with bcbio, but I still receive this error, despite that bams in other samples that were not prealigned having the 1 vs chr1 between the respective GRCh37 and mm10 reference.fa(s).

Are you saying I need to set aligner to bwa in the yaml, where as I currently have it set to false? Will that work if the file input is a bam? Thanks.

**Comment by schelhorn** [comment]
Perhaps you could do a `samtools idxstats` on one of your prealigned BAMs and post its output as well as the content of your yaml here for further discussion? Disambiguation is explained in the docs, so make sure to have a look if you haven't already.

**Comment by roryk** [comment]
Hi @bwubb,

disambiguation needs to align to both reference genomes to run properly, so the aligner needs to be turned on for it to run, `bwa` would be a good choice. I updated the docs to mention this here: http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#alignment

**Comment by chapmanb** [comment]
Brad;
For the first problem, Rory is right on with the requirement for an aligner -- apologies to not have been more clear in my previous reply.

For your test run on the second problem -- it worked okay without generating any errors? Is this after upgrading VarDict? If so, you might want to try re-running the pipeline before sending anything along. The errors you saw previously could have been from an old version. If it's still failing consistently and you can identify a small test case that fails happy to look into that, but I hope the re-run will fix it.
'
Thanks much.

**Comment by bwubb** [comment]
Thank you for the help. Im sorry my first issue was user error instead of a real issue. I thought aligner was only for aligning fastqs. Analysis was successful after resetting to bwa.

I am in the process of rerunning a sample suffering from issue #2 from scratch.

**Comment by bwubb** [comment]
Issue #2 is still present. I upgraded to the latest developement, deleted the work dir, and reran the analysis with a single core.

```
[2015-12-22T05:21Z] Index BAM file: 1205PRT#3p2+-sort.nsorted.disambiguatedSpeciesA.sorted-noanalysis-prep.bam
[2015-12-22T05:21Z] Timing: variant calling
[2015-12-22T05:21Z] multiprocessing: variantcall_sample
[2015-12-22T05:21Z] Genotyping with VarDict: Inference
[2015-12-22T05:21Z] Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
[2015-12-22T05:21Z]   line 1 did not have 34 elements
[2015-12-22T05:21Z] Calls: read.table -> scan
[2015-12-22T05:21Z] Execution halted
[2015-12-22T05:21Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC -Djava.io.tmpdir=/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/tx/tmpDSwATC' && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#3p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/bamprep/1205PRT#3p2+/1/1205PRT#3p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22384017-prep.bam -c 1 -S 2 -E 3 -g 4 -Q 10 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/1205PRT#3p2+-1_0_22384017-raw-unmerged-regions-regionlimit.bed | teststrandbias.R| var2vcf_valid.pl -N 1205PRT#3p2+ -E -f 0.1  | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /home/bwubb/bcbio-tools/bin/vcfstreamsort | bgzip -c > /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/tx/tmpDSwATC/1205PRT#3p2+-1_0_22384017-raw.vcf.gz
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  line 1 did not have 34 elements
Calls: read.table -> scan
Execution halted
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 146, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 169, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 143, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 254, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 80, in run_vardict
    assoc_files, region, out_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 247, in _run_vardict_paired
    assoc_files, region, out_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 150, in _run_vardict_caller
    do.run(cmd.format(**locals()), "Genotyping with VarDict: Inference", {})
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC -Djava.io.tmpdir=/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/tx/tmpDSwATC' && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#3p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/bamprep/1205PRT#3p2+/1/1205PRT#3p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22384017-prep.bam -c 1 -S 2 -E 3 -g 4 -Q 10 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/1205PRT#3p2+-1_0_22384017-raw-unmerged-regions-regionlimit.bed | teststrandbias.R| var2vcf_valid.pl -N 1205PRT#3p2+ -E -f 0.1  | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /home/bwubb/bcbio-tools/bin/vcfstreamsort | bgzip -c > /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/tx/tmpDSwATC/1205PRT#3p2+-1_0_22384017-raw.vcf.gz
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  line 1 did not have 34 elements
Calls: read.table -> scan
Execution halted
' returned non-zero exit status 1
```

I hope I did not forget something...

Let me know what more I can do to help debug. Thank you.

**Comment by chapmanb** [comment]
Brad;
Sorry about the continued problems. vardict is having trouble with something in those files but unfortunately doesn't provide enough information in these error messages to help us debug. The R script fails because vardict is spitting out incorrect data so I guess we need to figure out the output. My suggestions for debugging are that you could send me this file off list and I could try to look at:
```
1205PRT#3p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22384017-prep.bam
```
or you could look at the output of:
```
export VAR_DICT_OPTS='-Xms750m -Xmx3500m -XX:+UseSerialGC && vardict-java -G /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 1205PRT#3p2+ -b /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/bamprep/1205PRT#3p2+/1/1205PRT#3p2+-sort.nsorted.disambiguatedSpeciesA.sorted-1_0_22384017-prep.bam -c 1 -S 2 -E 3 -g 4 -Q 10 /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205PRT#3p2+/work/vardict/1/1205PRT#3p2+-1_0_22384017-raw-unmerged-regions-regionlimit.bed 
```
to determine if something looks wrong.

Sorry to not have a more detailed idea of the problem but hope this helps some.
