### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1618]
Hi Brad,
I met the following error during the alignment. Could you please help me with it?
Thanks.

[2016-10-28T00:43Z] ***.edu: Aligning lane 34_2016-10-25_12th_s-merged with bwa aligner
[2016-10-28T00:48Z] ***.edu: ipython: delayed_bam_merge
[2016-10-28T01:41Z] ***.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; bamcat level=0 tmpfile=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam-bammerge `cat /path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.list` | bamsormadup threads=16 indexfilename=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam.bai tmpfile=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam-bamsormaduptmp > /path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam
[V] 9437184
[V] 10013915	01:11:43320900	MemUsage(size=4295.94,rss=1687.65,peak=4295.94)	AutoArrayMemUsage(memusage=3253.13,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 10485760
[V] 10849591	01:17:53226499	MemUsage(size=4295.94,rss=1687.66,peak=4295.94)	AutoArrayMemUsage(memusage=3253.13,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 11534336
[V] 11685116	01:23:50620800	MemUsage(size=4295.94,rss=1687.67,peak=4295.94)	AutoArrayMemUsage(memusage=3253.13,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 12582912
[V] 13356499	01:35:33790899	MemUsage(size=4295.94,rss=1687.69,peak=4295.94)	AutoArrayMemUsage(memusage=3253.13,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 13631488
[V] 14192064	01:41:36085799	MemUsage(size=4295.94,rss=1687.7,peak=4295.94)	AutoArrayMemUsage(memusage=3253.13,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 14680064
[V] 15027599	01:47:44219999	MemUsage(size=4295.94,rss=1687.71,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 15728640
[V] 15863379	01:53:43113499	MemUsage(size=4295.94,rss=1687.74,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 16777216
[V] 17533993	02:03:96918300	MemUsage(size=4295.94,rss=1687.78,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 17825792
[V] 18369643	02:09:96069600	MemUsage(size=4295.94,rss=1687.82,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 18874368
[V] 19205274	02:16:00798000	MemUsage(size=4295.94,rss=1687.82,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 19922944
[V] 20040172	02:21:97972500	MemUsage(size=4295.94,rss=1687.83,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 20971520
[V] 21711417	02:33:99166999	MemUsage(size=4295.94,rss=1687.85,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 22020096
[V] 22547087	02:39:92344299	MemUsage(size=4295.94,rss=1687.85,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 23068672
[V] 23382717	02:45:86329900	MemUsage(size=4295.94,rss=1687.86,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 24117248
[V] 24218317	02:51:82016500	MemUsage(size=4295.94,rss=1687.86,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 25165824
[V] 25889640	03:03:77515900	MemUsage(size=4295.94,rss=1687.88,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 26214400
[V] 26725447	03:08:37070499	MemUsage(size=4295.94,rss=1687.88,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 27262976
[V] 27561170	03:14:40763100	MemUsage(size=4295.94,rss=1687.89,peak=4295.94)	AutoArrayMemUsage(memusage=3253.14,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 28311552
[V] 28396977	03:20:41770999	MemUsage(size=4295.94,rss=1687.89,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 29360128
[V] 30068331	03:32:33018999	MemUsage(size=4295.94,rss=1687.91,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 30408704
[V] 30904004	03:38:46516700	MemUsage(size=4295.94,rss=1687.91,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 31457280
[V] 31739716	03:44:51886200	MemUsage(size=4295.94,rss=1687.92,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 32505856
[V] 32575406	03:50:60727600	MemUsage(size=4295.94,rss=1687.98,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 33554432
[V] 34245987	04:02:63333800	MemUsage(size=4295.94,rss=1688.04,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 34603008
[V] 35081568	04:07:23638800	MemUsage(size=4295.94,rss=1688.05,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 35651584
[V] 35915177	04:13:30606499	MemUsage(size=4295.94,rss=1688.06,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 36700160
[V] 36749818	04:19:30507599	MemUsage(size=4295.94,rss=1688.12,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 37748736
[V] 38419870	04:31:38149199	MemUsage(size=4295.94,rss=1688.14,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 38797312
[V] 39255555	04:37:38338199	MemUsage(size=4295.94,rss=1688.15,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 39845888
[V] 40091199	04:43:34392000	MemUsage(size=4295.94,rss=1688.16,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 40894464
[V] 40926891	04:49:46452199	MemUsage(size=4295.94,rss=1688.14,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 41943040
[V] 42598302	05:01:48493799	MemUsage(size=4295.94,rss=1688.17,peak=4295.94)	AutoArrayMemUsage(memusage=3253.15,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 42991616
[V] 43433978	05:06:10728299	MemUsage(size=4295.94,rss=1688.14,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 44040192
[V] 44269662	05:12:07485800	MemUsage(size=4295.94,rss=1688.18,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 45088768
[V] 45105354	05:18:11160000	MemUsage(size=4295.94,rss=1688.18,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 46137344
[V] 46776691	05:30:06825300	MemUsage(size=4295.94,rss=1688.18,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 47185920
[V] 47612383	05:36:03384399	MemUsage(size=4295.94,rss=1688.18,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 48234496
[V] 48447928	05:42:03068000	MemUsage(size=4295.94,rss=1688.2,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 49283072
[V] 49283533	05:48:04031500	MemUsage(size=4295.94,rss=1688.2,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 50331648
[V] 50954972	06:00:41162000	MemUsage(size=4295.94,rss=1688.22,peak=4295.94)	AutoArrayMemUsage(memusage=3253.16,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 51380224
[V] 51790818	06:06:66139900	MemUsage(size=4295.94,rss=1688.24,peak=4295.94)	AutoArrayMemUsage(memusage=3253.17,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 52428800
[V] 52626479	06:11:47799600	MemUsage(size=4295.94,rss=1688.26,peak=4295.94)	AutoArrayMemUsage(memusage=3253.17,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 53477376
[V] 54297730	06:24:13398699	MemUsage(size=4295.94,rss=1688.3,peak=4295.94)	AutoArrayMemUsage(memusage=3253.17,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 54525952
[V] 55133379	06:30:53207500	MemUsage(size=4295.94,rss=1688.3,peak=4295.94)	AutoArrayMemUsage(memusage=3253.17,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 55574528
[V] 55970059	06:36:82894199	MemUsage(size=4295.94,rss=1688.34,peak=4295.94)	AutoArrayMemUsage(memusage=3253.17,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 56623104
[V] 56807014	06:42:99289900	MemUsage(size=4295.96,rss=1688.38,peak=4295.96)	AutoArrayMemUsage(memusage=3253.2,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 57671680
[V] 58480430	06:55:55273099	MemUsage(size=4295.96,rss=1688.45,peak=4295.96)	AutoArrayMemUsage(memusage=3253.21,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 58720256
[V] 59316528	07:01:86143600	MemUsage(size=4295.96,rss=1688.48,peak=4295.96)	AutoArrayMemUsage(memusage=3253.21,peakmemusage=3420.34,maxmem=1.75922e+13)
[V] 59768832
[V] 60152503	07:08:22652599	MemUsage(size=4295.96,rss=1688.5,peak=4295.96)	AutoArrayMemUsage(memusage=3253.21,peakmemusage=3420.34,maxmem=1.75922e+13)
/bin/bash: line 1: 63709 Segmentation fault      bamcat level=0 tmpfile=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam-bammerge `cat /path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.list`
     63710                       | bamsormadup threads=16 indexfilename=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam.bai tmpfile=/path/to/project/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam-bamsormaduptmp > /lustre/work/unmc_gudalab/pxiao/cowan/12th_s/work/align/1281T/tx/tmpjgoyyw/1281T-sort.bam
' returned non-zero exit status 139

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issues. Typically we've seen core dumps from bamsormadup at this point due to memory constraints on the system. From the log and command line it looks like you're running on 16 core machines with ~35Gb of memory. It appears that sorting here takes more than ~2Gb/core memory, which I believe is the cause of the issue.

I pushed a fix to the latest development (`bcbio_nextgen.py upgrade -u development`) which tries to avoid this by scaling down cores based on an expected memory usage. If you update and re-try the pipeline I hope it will now get past this step. Thanks again for the report.

**Comment by pengxiao78** [comment]
Thank you, Brad. Before your giving me the suggestion, I deleted all the bcbio-nextgen and tried to install it from the beginning but found the following error. I tried conda clean --lock command but the error still appeared. Could you help me to solve this problem?
Thanks again.

pyfaidx-0.4.1.   0% |                              | ETA:  --:--:--   0.00  B/s
pyfaidx-0.4.1.  60% |##################             | Time: 0:00:00 491.39 kB/s
pyfaidx-0.4.1. 100% |###############################| Time: 0:00:00 406.16 kB/s
pyfaidx-0.4.1. 100% |###############################| Time: 0:00:00 399.92 kB/s
Exceeded max retries, giving up

LockError: Lock error: Already locked: Lock error: 
LOCKERROR: It looks like conda is already doing something.
The lock [u'/path/to/bcbio/anaconda/pkgs/pyfaidx-0.4.1.1-py27_0.tar.bz2.pid58074.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock

**Comment by chapmanb** [comment]
I haven't seen this error before so I'm not sure about the best solution. I'd first run:
```
bcbio_conda clean --lock
```
if case `conda` on your machine points to a different conda installation. If that doesn't work I'd manually remove the locked file:
```
rm -f /path/to/bcbio/anaconda/pkgs/pyfaidx-0.4.1.1-py27_0.tar.bz2.pid58074.conda_lock
```
Hope this fixes it for you

**Comment by pengxiao78** [comment]
Hi Brad,

Thanks. I will try to see if this will work. However, I have another problem on another cluster computer that I have successfully updated the bcbio-nextgen into the development by command bcbio_nextgen.py upgrade -u development. When I ran it, I found the following java version problem. I have updated GATK into 3.6 and the stable version did not have this problem. How could this happen in the development version? Could you help me to debug it?

Thanks again.


[2016-11-01T19:45Z] ica1: Testing minimum versions of installed programs
[2016-11-01T19:45Z] ica1: Unexpected error
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 456, in organize_samples
    return ipython.zip_args(apply(run_info.organize, *args))
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 78, in organize
    out = _add_provenance(out, dirs, config, add_provenance)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 91, in _add_provenance
    versioncheck.testall(items)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/versioncheck.py", line 84, in testall
    "\n".join(msgs))
OSError: Program problems found. You can upgrade dependencies with:
bcbio_nextgen.py upgrade -u skip --tooldir=/usr/local

java version 1.7 required for running MuTect and GATK < 3.6. Found version 1.8.0_92 at /path/to/bcbio/anaconda/bin/java

**Comment by chapmanb** [comment]
If you want to run pre-3.6 versions of GATK, or MuTect, you need to have Java 1.7 available so that running `java -version` gives the 1.7 version. It looks like you have the bcbio anaconda directory in your PATH first which picks up the Java 1.8 version bcbio provides. Older versions of GATK are only compatible with 1.7. So if you adjust your PATH so a Java 1.7 is first it should resolve this issue. Hope this helps.

**Comment by pengxiao78** [comment]
Hi Brad,

The problem is that I have deleted all the previous bcbio-nextgen including all the files, folders, tools, and data. Then, I installed and updated the version into stable 0.99 and also GATA 3.6 without any MuTect since the MuTect 2 is distributed with GATA 3.6. The above alignment error was in this stable version 0.99 but no Java version problem because GATK 3.6 needs Java 1.8. However, after I upgraded bcbio-nextgen into the development version, this incompatibility appeared. I did checked the toolplus and bcbio_system.yaml file and did not find any pre-3.6 GATK or any MuTect tool. The content of bcbio_system.yaml is as follows. 

galaxy_config: universe_wsgi.ini
resources:
  default:
    cores: 16
    jvm_opts:
    - -Xms750m
    - -Xmx3500m
    memory: 3G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  gatk:
    dir: /path/to/bcbio/toolplus/gatk/3.6-0-g89b7209
    jvm_opts:
    - -Xms500m
    - -Xmx3500m
  macs2:
    memory: 8g
  qualimap:
    memory: 4g
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
    - -Xms750m
    - -Xmx4g

My question is if the upgrading of development version cause the confusion and error.

Thanks.

**Comment by chapmanb** [comment]
The development version should help with GATK 3.6/Java issues, but perhaps this is a problem with how you setup GATK. There is a new approach to including it within bcbio using gatk-register:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

Hopefully doing that will get things going for you.

**Comment by pengxiao78** [comment]
I ran the 

gatk-register /path/to/GenomeAnalysisTK-3.6.tar.bz2

and ran the cancer variant calling slurm,  coming with the same error: java version 1.7 required for running MuTect and GATK < 3.6. Found version 1.8.0_92 at /path/to/bcbio/anaconda/bin/java

Since I used the old way to install GATK 3.6 previously, the system may still have some old version of GATK or MuTect in somewhere. Do you have any suggestion to let bcbio-nextgen recognize the new GATK and deleting the old versions?

Thanks.

**Comment by chapmanb** [comment]
Sorry about the continued problems. I'm not sure what is going on here, as it should prefer the `gatk-register` version over any other registered versions. Could we see your sample YAML configuration? It is possible it specifies mutect which is causing the issue? Thanks for the help debugging.

**Comment by pengxiao78** [comment]
Hi Brad,
Yes, you are right. In my YAML file, I had mutect in the variant caller. But when I changed it into mutect2, it did work and started to run.
Thanks!
