### ISSUE TITLE
bcbio-nextgen install pysam issue

### ISSUE THREAD

**Issue by davidballi** [chapmanb/bcbio-nextgen#1873]
I am trying to install bcbio-nextgen in a fresh EC2 Ubuntu Server 14.04 (ami-d05e75b8), but I'm receiving the following error on install:

```
$ sudo apt-get update
$ sudo apt-get install -y build-essential zlib1g-dev wget curl python-setuptools git \
                        openjdk-7-jdk openjdk-7-jre ruby libncurses5-dev libcurl4-openssl-dev \
                        libbz2-dev unzip pigz bsdmainutils python-minimal python-pip python-dev awscli tree

$ wget https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py

$sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir /usr/local --genomes hg38 --aligners hisat2 --isolate --u stable --distribution ubuntu

Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2017-03-21 16:06:36--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.32.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

100%[==========================================================================================================================================================================>] 20          --.-K/s   in 0s

2017-03-21 16:06:36 (3.05 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /usr/local/share/bcbio/anaconda:
#
bcbio-nextgen             1.0.2                    py27_0    bioconda
Installing data and third party dependencies
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, utils, workflow
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 25, in <module>
    from bcbio import broad, utils
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 16, in <module>
    from bcbio.broad import picardrun
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 6, in <module>
    import pysam
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
**ImportError: libhts.so.1: cannot open shared object file: No such file or directory**
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir', '/usr/local', '--genomes', 'hg38', '--aligners', 'hisat2', '--isolate', '--u', 'stable', '--distribution', 'ubuntu', '--data']' returned non-zero exit status 1
```

I tried `sudo pip install pysam` but that didn't resolve the issue.  Any thoughts?

**Comment by i-mtz** [comment]
I just had the same issue using debian 8. 
It seems that the pysam recipe is missing some htslib files (libhts.so.1), although htslib 1.4 is installed and gives no errors.

This is happens if I use both pysam 0.10 and 0.9, using pysam 0.8.3 works fine. 
Here's the ldd output from  libchtslib.so for pysam 0.9 and 0.10

	linux-vdso.so.1 (0x00007fffa12e7000)
	libz.so.1 => /build/tests/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pysam/./../../../libz.so.1 (0x00007f0fdf2bc000)
	libhts.so.1 => not found
	libpython2.7.so.1.0 => /build/tests/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pysam/./../../../libpython2.7.so.1.0 (0x00007f0fdeec0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0fdeca3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0fde8f8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0fde6f4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0fde4f1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0fde1f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0fdf6d6000)


And for the working pysam:

	linux-vdso.so.1 (0x00007ffd5eb25000)
	libz.so.1 => /build/tests/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pysam/./../../../libz.so.1 (0x00007f3043406000)
	libpython2.7.so.1.0 => /build/tests/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pysam/./../../../libpython2.7.so.1.0 (0x00007f304300a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3042ded000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3042a42000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f304283e000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f304263b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f304233a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f30438a5000)

**Comment by chapmanb** [comment]
David and @i-mtz 
Thanks for the heads up and apologies about the problem. It looks like the pysam folks are still working on htslib 1.4 compatibility as there are some API changes:

https://github.com/pysam-developers/pysam/issues/413

I swapped back to the 1.3 version in bcbio for now to avoid the problem so if you either update `--tools` or do: `bcbio_conda install -c bioconda htslib=1.3` it should resolve the issue. Thanks again for reporting this.

**Comment by davidballi** [comment]
Hi Brad, thanks for the quick response and fix.  Still having an issue switching to htslib=1.3.  I can't run the `bcbio_conda install -c bioconda htslib=1.3` as I can't install bcbio_nextgen.  

I tried:
``` 
conda install -c bioconda htslib=1.3
# and then
sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir /usr/local --genomes hg38 --aligners hisat2 --isolate --u stable --distribution ubuntu
```

but I'm still receiving an error.  thanks for your patience.

**Comment by chapmanb** [comment]
David;
Thanks for following up. A couple of suggestions to try:

- Is the `conda` in your first command the conda installed by bcbio (it should be in `/usr/local/share/bcbio/anaconda/bin/conda`)? You need to update the htslib here, in case `conda` in your PATH points somewhere else.
- Do you have a `tmpbcbio-install` directory left over from a previous install? If so, remove that as it could pull in the old htslib recommendation and re-install 1.4.

Also, I'd suggest not running the installer with sudo or as root. You can install bcbio anywhere and include in your PATH or chmod the `/usr/local/` directories so your non-priviliged user can install there.

Hope this helps.

**Comment by davidballi** [comment]
yes that was it.  I was using a different conda.. running: `sudo /usr/local/share/bcbio/anaconda/exec/conda install -c bioconda htslib=1.3` and the installation is now working.

thanks again.
