### ISSUE TITLE
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by maschaefer** [chapmanb/bcbio-nextgen#1878]
Hi,

I am running a variant calling pipeline including qsignature mixup check on a cluster with a PBS pro batch system.
Recently, after installation of the libxml2-dev package, I first got the error handled in #1850, which of course disappeared after updating bcbio.
Now afterwards, I am encountering the following problems due to dependency issues with the conda package icu:

[2017-03-27T15:48Z] multiprocessing: qsignature_summary
Traceback (most recent call last):
  File "/software/bcbio//anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/software/bcbio//anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 188, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 37, in generate_parallel
    qsign_info = run_parallel("qsignature_summary", [samples])
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 189, in qsignature_summary
    return qsignature.summary(*args)
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qsignature.py", line 110, in summary
    out_warn_file, samples[0][0])
  File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qsignature.py", line 129, in _parse_qsignature_output
    import lxml.etree
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

Sounds to me like icu isn’t installed in the needed way in bcbio’s conda? The issue is independent of whether I use ipython parallelization or not, and cannot be solved by setting mixup_check: false.

Many thanks in advance for help!
Martin

**Comment by chapmanb** [comment]
Martin;
Sorry about the issue. We've been working on trying to resolve this problem and the underlying issue is that there are different versions of lxml compiled against different versions of cui (56 and 58). We've been trying to stabilize on 58 which I thought was in place but apparently did not work in your update. To fix you should hopefully be able to do:
```
bcbio_conda install -c conda-forge 'icu=58.*' lxml
```
Hope this gets it working for you

**Comment by lpantano** [comment]
Hi Maritn,

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!

**Comment by apastore** [comment]
Hi,I have just noticed  if I run upgrade my bcbio to the last develop version I get downgrade to ICU-56, and If I conda install icu=58.1 I get downgrade delly, sailfish und salmon.


The following packages will be UPDATED:

    delly:      0.7.6-0            bioconda    --> 0.7.7-boost1.61_1  bioconda   
    sailfish:   0.9.0-1            bioconda    --> 0.10.1-boost1.61_0 bioconda   
    salmon:     0.8.1-0            bioconda    --> 0.8.2-0            bioconda   

The following packages will be DOWNGRADED due to dependency conflicts:

    boost:      1.64.0-np112py27_1 conda-forge --> 1.61.0-py27_1      conda-forge
    boost-cpp:  1.64.0-0           conda-forge --> 1.63.0-1           conda-forge
    cairo:      1.14.6-4           conda-forge --> 1.14.6-0           conda-forge
    fontconfig: 2.12.1-4           conda-forge --> 2.11.1-6           conda-forge
    freetype:   2.7-1              conda-forge --> 2.6.3-1            conda-forge
    harfbuzz:   1.4.3-0            conda-forge --> 1.3.4-0            conda-forge
    icu:        58.1-1             conda-forge --> 56.1-4             conda-forge
    libgd:      2.2.4-1            conda-forge --> 2.2.3-1            conda-forge
    matplotlib: 2.0.0-np112py27_2  conda-forge --> 2.0.0-np112py27_1  conda-forge
    pango:      1.40.4-0           conda-forge --> 1.40.3-0           conda-forge
    pillow:     4.1.1-py27_0       conda-forge --> 4.0.0-py27_1       conda-forge
    qt:         4.8.7-7            conda-forge --> 4.8.7-6            conda-forge

**Comment by DoaneAS** [comment]
I'm also seeing this issue toward the end of RNAseq runs, related to xml parsing.  Installing icu=58 would downgrade salmon to 8.1.

`    277 def _parse_rnaseq_qualimap_metrics(report_file):
    278     """Extract useful metrics from the qualimap HTML report file.
    279     """
--> 280     import lxml.html
    281     out = {}
    282     parsers = ["Reads alignment", "Reads genomic origin", "Transcript coverage profile"]
    283     root = lxml.html.parse(report_file).getroot()
    284     for table in root.xpath("//div[@class='table-summary']"):
`

**Comment by apastore** [comment]
Hi Ashley, (just in case you do not have any workaround on this). my quick fix was to set tools_off: qualimap in the configuration template.yaml file,  and comment in  qcsummary.py this two line in the _run_qc_tools function:

             "qualimap": qualimap.run,
             "qualimap_rnaseq": qualimap.run_rnaseq,

Alessandro

**Comment by chapmanb** [comment]
Alessandro and Ashley;
Thanks for reporting this and sorry about the issues cropping up again. There are two different issues here:

- `icu` can resolve to different versions depending on the packages installed, resulting in installs of 56 or 58. This breaks `lxml` if it's not on 58.
- salmon and sailfish are only building correctly with boost 1.63.0, while bioconda boost is at 1.61.0. Tools like delly that link to 1.61.0 can cause regressions in the salmon/sailfish versions. This thread has more details about the boost (and icu) issues: https://github.com/bioconda/bioconda-recipes/pull/4208

I'm not sure about the best way to improve the sailfish/salmon problem now since I also can't get it to build with boost 1.61.0, but I pushed a fix to development to avoid the lxml icu errors. We now use beautifulsoup and the native python `xml` library for parsing HTML and XML, respectively, so lxml is no longer a dependency.

Hope this helps make things better and we'll keep an eye on improving the salmon boost install issues.

**Comment by apastore** [comment]
Hi Brad, Thanks a lot for switching to beautifulsoup. I still get this error if I run the qc for RNA seq.
Thanks a lot!

Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 277, in pipeline_summary
    return ipython.zip_args(apply(qcsummary.pipeline_summary, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 66, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 136, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 323, in run_rnaseq
    metrics = _parse_metrics(metrics)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 191, in _parse_metrics
    total_reads = sum([int(metrics[name]) for name in total])
ValueError: invalid literal for int() with base 10: 'nan'

**Comment by chapmanb** [comment]
Alessandro;
Thanks for reporting this. I pushed a fix which should correctly handle non-integer values for these when converting over. If you update to the latest development version and re-run your analysis it should pick up where it left off and hopefully work cleanly. Please let us know if you run into any other issues.

**Comment by apastore** [comment]
Thanks!
