### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by choosehappy** [chapmanb/bcbio-nextgen#2158]
this is on what i imagine is a typical paired normal/tumor sample, and i upgraded the stable version last night. Any thoughts?

```
[2017-11-15T06:43Z] multiprocessing: calculate_sv_bins
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 131, in variant2pipeline
    samples = run_parallel("calculate_sv_bins", [samples])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 287, in calculate_sv_bins
    return svregions.calculate_sv_bins(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 44, in calculate_sv_bins
    work_dir, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 384, in targets_w_bins
    target_bin, _ = target_anti_fn()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 67, in get_target_antitarget_bin_sizes
    self.result = self._calc_sizes(self.cnv_file, self.items)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 106, in _calc_sizes
    raw_anti_bin = bp_per_bin / float(np.median(anti_bps))
ZeroDivisionError: float division by zero

```

**Comment by chapmanb** [comment]
Thanks much for the report and sorry about the problem. It looks like you sample might have all zero anti-target regions, causing this error. I added a boundary check to avoid this to latest development so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run, hopefully it'll do the right thing and finish your analysis. Please let us know if you run into any other issues.

**Comment by choosehappy** [comment]
sorry to be a pain, but this in fact raised an unrelated error, not sure if i should open a new ticket or not?

```
java version 1.7 required for running MuTect and GATK < 3.6.
It needs to be first on your PATH so running 'java -version' give the correct version.
Found version 1.8.0_121 at /usr/local/share/bcbio-nextgen/anaconda/bin/java
```


but in fact, the java on the path is version 1.7, yet the one found is version 1.8:

```
root@51853b033dc8:/data/CNV.valid# java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
root@51853b033dc8:/data/CNV.valid# /usr/local/share/bcbio-nextgen/anaconda/bin/java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)
root@51853b033dc8:/data/CNV.valid# 
```
We have the older java version in place for use with the older MuTect.

We noticed that you moved over to MuTect2, but we were unsure of its stability and performance which is why we were staying with the previous version (we had experienced a number of bugs and false positives about 6 months ago). 

Do you have some insights if those are still an issue? We can likely move to mutect2 to simply ignore this problem :)

**Comment by chapmanb** [comment]
Apologies about the issue. We have some recent changes in the development version to try and avoid users needing to set their external paths, but this inadvertently preferred the bcbio installed java 8 over the external java 7 for these uses. I pushed a fix to the latest development version to avoid this, so if you update you should now be able to run cleanly with MuTect. Sorry again about the issues and please let us know if you get stuck anywhere else.

On MuTect2 vs MuTect, they both have their uses. MuTect2 is improving but we've also found that MuTect can outperform it on some samples (as long you're okay with SNP-only calling). I don't yet have a good sense of pre-defining the samples where each does better but generally lower noise samples seem to do better with MuTect2 while it has more false positives if you have increased sequencing noise. Hope this helps.

**Comment by choosehappy** [comment]
seems to have resolved both errors! thanks!

a new one kicked up, but i'm unsure if its because due to the previous errors the sample was left in an unsane state:

```
[2017-11-16T16:17Z]     "                                                 chr22_KI270737v1_random:33199-33393      log2=1.191  spread=1.765  rmask=nan
[2017-11-16T16:18Z] Wrote /data/CNV.valid/P1/work/bcbiotx/tmpYoeEUy/background-0-cnvkit.cnn with 2892498 regions
[2017-11-16T16:18Z] CNVkit fix
[2017-11-16T16:18Z] Processing target: T1
[2017-11-16T16:18Z] Traceback (most recent call last):
[2017-11-16T16:18Z]   File "/usr/local/share/bcbio-nextgen/anaconda/bin/cnvkit.py", line 13, in <module>
[2017-11-16T16:18Z]     args.func(args)
[2017-11-16T16:18Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 562, in _cmd_fix
[2017-11-16T16:18Z]     args.do_gc, args.do_edge, args.do_rmask)
[2017-11-16T16:18Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 19, in do_fix
[2017-11-16T16:18Z]     do_gc, do_edge, False)
[2017-11-16T16:18Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 64, in load_adjust_coverages
[2017-11-16T16:18Z]     ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
[2017-11-16T16:18Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 130, in match_ref_to_sample
[2017-11-16T16:18Z]     " set:\n" + "\n".join(map(str, dset.index[dupes])))
[2017-11-16T16:18Z] ValueError: Duplicated genomic coordinates in sample set:
[2017-11-16T16:18Z] Pandas(chromosome='chr1', start=3590950, end=3590952)
[2017-11-16T16:18Z] Pandas(chromosome='chr1', start=11768896, end=11768901)
```
I've deleted the entire working directory and will start the processing from scratch, should be able to confirm if its still an issue in a few hours.

also, thank you for your insights on mutect, we've come to a similar conclusion. ultimately i think people are likely to keep using the version that they were taught with until compelled by benchmarks to move to the new version. time will tell!

**Comment by choosehappy** [comment]
Actually it seems it didn't even get that far. crashed out at GATK , i'm guessing the crux is:

`##### ERROR MESSAGE: Argument with name 'jdk_deflater' isn't defined.`

here is the full stack:

```
[2017-11-16T22:47Z] Applying BQSR recalibration with GATK: N1
[2017-11-16T22:47Z] GATK: PrintReads
[2017-11-16T22:47Z] ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-16T22:47Z] ##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4):
[2017-11-16T22:47Z] ##### ERROR
[2017-11-16T22:47Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2017-11-16T22:47Z] ##### ERROR The error message below tells you what is the problem.
[2017-11-16T22:47Z] ##### ERROR
[2017-11-16T22:47Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2017-11-16T22:47Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2017-11-16T22:47Z] ##### ERROR
[2017-11-16T22:47Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms500m -Xmx22932m -Djava.io.tmpdir=/data/CNV.valid/P1/work/bcbiotx/tmp3lye8B -jar /usr/local/share/bcbio-nextgen/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T PrintReads -R /usr
/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa -I /data/CNV.valid/P1/work/align/N1/N1-sort.bam -BQSR /data/CNV.valid/P1/work/align/N1/N1-sort-recal.grp -o /data/CNV.valid/P1/work/bcbiotx/tmp3lye8B/N1-sort-recal.bam -jdk_def
later -jdk_inflater -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4):
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Argument with name 'jdk_deflater' isn't defined.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 237, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 129, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 131, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 246, in postprocess_alignment
    data = recalibrate.apply_recal(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 47, in apply_recal
    data["work_bam"] = _gatk_apply_bqsr(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 139, in _gatk_apply_bqsr
    parallel_gc=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 333, in run_gatk
    log_error=log_error)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms500m -Xmx22932m -Djava.io.tmpdir=/data/CNV.valid/P1/work/bcbiotx/tmp3lye8B -jar /usr/local/share/bcbio-nextgen/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T PrintRe
ads -R /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa -I /data/CNV.valid/P1/work/align/N1/N1-sort.bam -BQSR /data/CNV.valid/P1/work/align/N1/N1-sort-recal.grp -o /data/CNV.valid/P1/work/bcbiotx/tmp3lye8B/N1-sort-recal.b
am -jdk_deflater -jdk_inflater -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4):
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Argument with name 'jdk_deflater' isn't defined.
##### ERROR ------------------------------------------------------------------------------------------

```

**Comment by chapmanb** [comment]
Thanks much for retesting the run and apologies about the GATK issue. We were working around issues with the Intel deflater here but that is not present in older versions of GATK. I pushed a fix to only apply these options to recent versions that have it, so if you update to the latest development and re-run in place it should hopefully get past this point. Thanks again for the help debugging.

**Comment by choosehappy** [comment]
well after restarting the pipeline from scracth, the the duplication error seems to in fact be real. I have another sample i can test it on now to see if its persistent:

```

[2017-11-17T23:12Z]     "                                                 chr22_KI270736v1_random:180137-180390    log2=1.422  spread=2.108  rmask=nan
[2017-11-17T23:12Z]     "                                                 chr22_KI270736v1_random:180646-180900    log2=-0.886  spread=1.314  rmask=nan
[2017-11-17T23:12Z]     "                                                 chr22_KI270736v1_random:181411-181665    log2=-1.063  spread=1.575  rmask=nan
[2017-11-17T23:12Z]     "                                                 chr22_KI270737v1_random:33005-33198      log2=0.975  spread=1.446  rmask=nan
[2017-11-17T23:12Z]     "                                                 chr22_KI270737v1_random:33199-33393      log2=1.191  spread=1.765  rmask=nan
[2017-11-17T23:12Z] Wrote /data/CNV.valid/P1/work/bcbiotx/tmpzgfu0_/background-0-cnvkit.cnn with 2892498 regions
[2017-11-17T23:12Z] CNVkit fix
[2017-11-17T23:12Z] Processing target: T1
[2017-11-17T23:13Z] Traceback (most recent call last):
[2017-11-17T23:13Z]   File "/usr/local/share/bcbio-nextgen/anaconda/bin/cnvkit.py", line 13, in <module>
[2017-11-17T23:13Z]     args.func(args)
[2017-11-17T23:13Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 562, in _cmd_fix
[2017-11-17T23:13Z]     args.do_gc, args.do_edge, args.do_rmask)
[2017-11-17T23:13Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 19, in do_fix
[2017-11-17T23:13Z]     do_gc, do_edge, False)
[2017-11-17T23:13Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 64, in load_adjust_coverages
[2017-11-17T23:13Z]     ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
[2017-11-17T23:13Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 130, in match_ref_to_sample
[2017-11-17T23:13Z]     " set:\n" + "\n".join(map(str, dset.index[dupes])))
[2017-11-17T23:13Z] ValueError: Duplicated genomic coordinates in sample set:
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=3590950, end=3590952)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=11768896, end=11768901)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=22571945, end=22571948)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=22571945, end=22571948)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=23437944, end=23437950)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=23437944, end=23437950)
[2017-11-17T23:13Z] Pandas(chromosome='chr1', start=23437944, end=23437950)


----snip---

[2017-11-17T23:13Z] Pandas(chromosome='chr22', start=46630813, end=46630820)
[2017-11-17T23:13Z] Pandas(chromosome='chr22', start=46708828, end=46708831)
[2017-11-17T23:13Z] Pandas(chromosome='chr22', start=49825196, end=49825203)
[2017-11-17T23:13Z] Pandas(chromosome='chrX', start=80046782, end=80046789)
[2017-11-17T23:13Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export TMPDIR=/data/CNV.valid/P1/work/bcbiotx/tmpxge5cx && /usr/local/share/bcbio-nextgen/anaconda/bin/cnvkit.py fix -o /data/CNV.valid/P1/work/bcbiotx/tmpxge5cx/T1-normalized.cnr /data/CNV.v
alid/P1/work/structural/T1/bins/T1-target-coverage.cnn /data/CNV.valid/P1/work/structural/T1/bins/T1-antitarget-coverage.cnn /data/CNV.valid/P1/work/structural/T1/bins/background-0-cnvkit.cnn --sample-id T1
Pandas(chromosome='chr16', start=7357230, end=7357235)
Pandas(chromosome='chr16', start=7357230, end=7357235)
Pandas(chromosome='chr16', start=7357230, end=7357235)
Pandas(chromosome='chr16', start=7357230, end=7357235)
Pandas(chromosome='chr16', start=7357230, end=7357235)

```

**Comment by choosehappy** [comment]
Same error (though of course different genomic locations) when using a second different sample with the same pipeline

**Comment by chapmanb** [comment]
Thanks so much for the detailed reports and working to track this down. I've been trying to reproduce this issue but not yet had any luck. I'd love to get any suggestions from @etal but here would be my approach to debug. To take your first example, where you see duplicate segments in, for instance, `chr16:7357230-7357235`, can you see the source of that duplication in the three input files, either the target, antitarget or background:
```
/data/CNV.valid/P1/work/structural/T1/bins/T1-target-coverage.cnn
/data/CNV.valid/P1/work/structural/T1/bins/T1-antitarget-coverage.cnn
/data/CNV.valid/P1/work/structural/T1/bins/background-0-cnvkit.cnn
```
Knowing this we could then trace back to the command that generates those to see if the inputs have duplicates in some ways or if something gets introduced there. Hopefully that would then help identify what is causing it and working to avoid the issue.

Thanks much for the help digging into this problem.

**Comment by choosehappy** [comment]
not sure what the results are supposed to look like, but it seem that that region is in there multiple times per file and in multiple files:


```
root@51853b033dc8:/data/CNV.valid/P1/work/structural/T1/bins# grep 7357230 *
T1-target-coverage.cnn:chr5     173572114       173572309       CTB-33O18.1     -1.358  0.39
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
T1-target-coverage.cnn:chr16    7357230 7357235 RBFOX1  0.000   1.00
background-0-cnvkit.cnn:chr5    173572114       173572309       CTB-33O18.1     0       1       0.410256                0
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -0.1085 0.8     0.4             0.160862
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -0.1085 0.8     0.4             0.160862
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -0.3445 0.8     0.4             0.510756
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.5165 0.8     0.4             2.24836
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.593  0.8     0.4             2.36178
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.5905 0.8     0.4             2.35808
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.597  0.8     0.4             2.36771
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.5985 0.8     0.4             2.36994
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.595  0.8     0.4             2.36475
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.597  0.8     0.4             2.36771
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.594  0.8     0.4             2.36326
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.578  0.8     0.4             2.33954
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.579  0.8     0.4             2.34103
background-0-cnvkit.cnn:chr16   7357230 7357235 RBFOX1  -1.574  0.8     0.4             2.33361

```

**Comment by chapmanb** [comment]
Thanks so much for the example, this helped a ton to identify the problem. When we annotate the coverage file with gene names, `bedtools closest` resulted in duplicated lines if a feature was exactly equal distance from multiple transcripts of the same name. I pushed a fix that will resolve these to a single line and hopefully avoid the issues. If you remove the problematic files:
```
rm -f coverage/*/*-annotated.bed
rm -rf structural/bins
rm -rf structural/*/bin
rm -rf structural/*/cnvkit
```
and re-run in place it should regenerate these, hopefully without the duplicates. Sorry about the issue and thank you again for the help in tracking down the problem.

**Comment by choosehappy** [comment]
okay it gets a bit further down and then this pops up, is it something that i've done unintentionally?

```
[2017-11-20T10:52Z] GATK: ReadBackedPhasing
[2017-11-20T10:52Z] INFO  10:52:43,323 HelpFormatter - --------------------------------------------------------------------------------
[2017-11-20T10:52Z] INFO  10:52:43,325 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.5-0-g36282e4, Compiled 2015/11/25 04:03:56
[2017-11-20T10:52Z] INFO  10:52:43,325 HelpFormatter - Copyright (c) 2010 The Broad Institute
[2017-11-20T10:52Z] INFO  10:52:43,325 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
[2017-11-20T10:52Z] INFO  10:52:43,328 HelpFormatter - Program Args: -T ReadBackedPhasing -R /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --variant /data/CNV.valid/P1/work/freebayes/chrY/b1-chrY_16087894_56675098-unph
ased.vcf.gz --out /data/CNV.valid/P1/work/bcbiotx/tmpRhiQib/b1-chrY_16087894_56675098-unphased.vcf-phased.gz --downsample_to_coverage 250 --downsampling_type BY_SAMPLE -I /data/CNV.valid/P1/work/bamprep/N1/chrY/N1-sort-recal-chrY_1608789
4_56675098-prep.bam -I /data/CNV.valid/P1/work/bamprep/T1/chrY/T1-sort-recal-chrY_16087894_56675098-prep.bam -L /data/CNV.valid/P1/work/freebayes/chrY/b1-chrY_16087894_56675098-unphased-regions.bed --interval_set_rule INTERSECTION -U LEN
IENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
[2017-11-20T10:52Z] INFO  10:52:43,331 HelpFormatter - Executing as root@51853b033dc8 on Linux 4.4.0-97-generic amd64; OpenJDK 64-Bit Server VM 1.7.0_151-b01.
[2017-11-20T10:52Z] INFO  10:52:43,331 HelpFormatter - Date/Time: 2017/11/20 10:52:43
[2017-11-20T10:52Z] INFO  10:52:43,331 HelpFormatter - --------------------------------------------------------------------------------
[2017-11-20T10:52Z] INFO  10:52:43,331 HelpFormatter - --------------------------------------------------------------------------------
[2017-11-20T10:52Z] INFO  10:52:43,386 GenomeAnalysisEngine - Strictness is SILENT
[2017-11-20T10:52Z] INFO  10:52:44,462 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 250
[2017-11-20T10:52Z] INFO  10:52:44,468 SAMDataSource$SAMReaders - Initializing SAMRecords in serial
[2017-11-20T10:52Z] INFO  10:52:48,975 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 4.51
[2017-11-20T10:52Z] INFO  10:52:51,002 GATKRunReport - Uploaded run statistics report to AWS S3
[2017-11-20T10:52Z] ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-20T10:52Z] ##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4):
[2017-11-20T10:52Z] ##### ERROR
[2017-11-20T10:52Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2017-11-20T10:52Z] ##### ERROR The error message below tells you what is the problem.
[2017-11-20T10:52Z] ##### ERROR
[2017-11-20T10:52Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2017-11-20T10:52Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2017-11-20T10:52Z] ##### ERROR
[2017-11-20T10:52Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2017-11-20T10:52Z] ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
[2017-11-20T10:52Z] ##### ERROR
[2017-11-20T10:52Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2017-11-20T10:52Z] ##### ERROR
[2017-11-20T10:52Z] ##### ERROR MESSAGE: An index is required, but none found., for input source: /data/CNV.valid/P1/work/freebayes/chrY/b1-chrY_16087894_56675098-unphased.vcf.gz
[2017-11-20T10:52Z] ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-20T10:52Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/data/CNV.valid/P1/work/bcbiotx/tmpSKIrEK -jar /usr/local/share/bcbio-nextgen/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T Re
adBackedPhasing -R /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --variant /data/CNV.valid/P1/work/freebayes/chrY/b1-chrY_16087894_56675098-unphased.vcf.gz --out /data/CNV.valid/P1/work/bcbiotx/tmpRhiQib/b1-chrY_160878
94_56675098-unphased.vcf-phased.gz --downsample_to_coverage 250 --downsampling_type BY_SAMPLE -I /data/CNV.valid/P1/work/bamprep/N1/chrY/N1-sort-recal-chrY_16087894_56675098-prep.bam -I /data/CNV.valid/P1/work/bamprep/T1/chrY/T1-sort-rec
al-chrY_16087894_56675098-prep.bam -L /data/CNV.valid/P1/work/freebayes/chrY/b1-chrY_16087894_56675098-unphased-regions.bed --interval_set_rule INTERSECTION -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignme
nt
INFO  10:52:43,323 HelpFormatter - --------------------------------------------------------------------------------
INFO  10:52:43,325 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.5-0-g36282e4, Compiled 2015/11/25 04:03:56
INFO  10:52:43,325 HelpFormatter - Copyright (c) 2010 The Broad Institute
INFO  10:52:43,325 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk

```

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the detailed error message. ReadBackedPhasing, via `phasing: gatk` is no longer a recommended option. HaplotypeCaller itself does phasing and GATK4 removes ReadBackedPhasing entirely. Apologies that the bcbio implementation had gotten stale; I've remove it from bcbio and updated the documentation accordingly. You can either update to the latest development version (which will ignore the phasing command) or remove it from your configuration. Hope this gets things running cleanly for you.

**Comment by choosehappy** [comment]
awesome. one sample has run all the way to completion. i'll start the second one from scratch (as opposed to from checkpoints) to confirm.

by the way, in stdout_warnings.txt, this warning appears:

```
WARNING: Failed to compile plugin LoF: Can't locate utr_splice.pl in @INC (@INC contains: /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/vep/Plugins /usr/local/share/bcbio-nextgen/anaconda/share/ensembl-vep-90.7-0/modules /usr/local/share/bcbio-nextgen/anaconda/share/ensembl-vep-90.7-0 /usr/local/share/bcbio-nextgen/anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /usr/local/share/bcbio-nextgen/anaconda/lib/perl5/site_perl/5.22.0 /usr/local/share/bcbio-nextgen/anaconda/lib/perl5/5.22.0/x86_64-linux-thread-multi /usr/local/share/bcbio-nextgen/anaconda/lib/perl5/5.22.0 .) at /usr/local/share/bcbio-nextgen/anaconda/share/ensembl-vep-90.7-0/LoF.pm line 35.
Compilation failed in require at (eval 39) line 2.
BEGIN failed--compilation aborted at (eval 39) line 2.

```
where in fact no file "utr_splice" (any extension) exists?

**Comment by chapmanb** [comment]
Great news that your analysis is now running cleanly, thanks for reporting back. Thanks also for the heads up on the Loftee issues with VEP. It looks like the plugin changed and requires additional files. I updated the ensembl-vep recipe to include these so if you run:
```
bcbio_conda install -c conda-forge -c bioconda ensembl-vep
```
you should get an updated version that works correctly. Thanks again.

**Comment by choosehappy** [comment]
getting closer, a different error in the stdout_warnings.txt file:

`WARNING: Failed to instantiate plugin LoF: Can't open /humgen/atgu1/fs03/birnbaum/loftee-dev/splice_data/donor_motifs/ese.txt: No such file or directory at /usr/local/share/bcbio-nextgen/anaconda/share/ensembl-vep-90.7-1/loftee_splice_utils.pl line 210`

**Comment by chapmanb** [comment]
Thanks for testing and apologies for the continued problems. I don't have a ready to go VEP test here so have been implementing a bit blindly, I appreciate you helping test this. I pushed a fix which I think will resolve this by setting the loftee data file path for splice inputs. Please let us know if you hit any other issues and thanks again.

**Comment by choosehappy** [comment]
All errors/warnings are gone
Great job and thank you very much!
