### ISSUE TITLE
Re-introducing parallel bgzip (pbgzip) during split align prep

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#975]
So I found the next bottleneck in our bcbio setup (there is an infinite sequence of these, so I'm not worrying too much about it). During sample/align preparation, bcbio converts `gzip`ed and BAM inputs into` bgzip`ed and `tabix`'d files for split alignment. However, the `gzip` to `bgzip` conversion is rather slow since it is running on only one core. Based on the [sources](https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/pipeline/tools.py#L27), it seems as if bcbio once used a parallel `pbgzip` implementation. In our local installation, I reinstalled `pbgzip` from a [samtools fork](https://github.com/nh13/samtools/tree/master/pbgzip) and it performs just fine, scaling up to 8 cores until the `gzip` input stream becomes the limiting factor. I was wondering is the segfault issues reported in the sources are still valid, and if it is possible or desirable for the official bcbio installation to move back to `pbgzip` at some point in time.

**Comment by chapmanb** [comment]
Sven-Eric;
It would be great if you'd like to investigate this. I'm agreed that bgzip is a big bottleneck and re-introducing parallel bgzip would be a nice improvement.

In my past experience, parallel bgzip would segfault on some samples without apparent cause. Or at least, I couldn't identify a single factor that caused it to fail in some cases and not in others, which didn't make it easy to produce reliable work/not work cases. I did do one pull request that seemed to improve things some:

https://github.com/nh13/samtools/pull/2

but it still failed after that and I kind of gave up as I don't really understand all of the magic in that branch. I was hoping someone would take this on and we'd have parallel bgzip but that didn't happen so we can re-examine.

I guess the next best step would be having a standard build of this and make it an option so we can start to find and categorize failure cases. Are you using the raw build from @nh13 implementation, or have adjusted at all? Thanks much.

**Comment by nh13** [comment]
I would be happy to help here too. 

Thumb typed for added typos

**Comment by schelhorn** [comment]
Thanks for chiming in, @nh13. Any help would be greatly appreciated, especially since I am not fluent in C. Perhaps it would be a good start if you could split up your `pbgzip` implementation into a separate repository as @chapmanb suggested? Perhaps Brad then could include that into the bcbio installation routine and/or biolinux. We could then allow activating the parallel `pbgzip` on-demand (labeled as _experimental_) in the `bcbio_system.yaml`, so that other bcbio users are protected from the random segfaults that Brad used to observed. More performance-conscious users like myself could activate `pbgzip` and we wait for the bug reports to come in to narrow down on a minimal failed input that generates a segfault. Does that make sense?

**Comment by guillermo-carrasco** [comment]
Hi everyone,

Sorry for jumping into the discussion, but I think the idea of an standalone implementation of pbgzip is a good one. 

@nh13 what do you think about that? 

@schelhorn the last commit to pbgzip is from [April 14th 2013](https://github.com/nh13/samtools/commit/6703d2ec955e97246e444ecf34c05bbbf458df8d), am I right? The discussion that Brad pointed out was in September that year, so I am not sure that the problem is solved. Unless Brad wasn't using the latest version at that time? 

The problem is that, as Brad pointed out, if the segfault happens randomly, it may be quite hard to point where the potential bug is. @chapmanb , any clue of how could we test it? Do you know about any particular sample where it always failed, or was it always random?

If we can't determine where the bug is exactly, then as Sven-Eric suggests, to label the integration as experimental may be an option. 

Thanks!

**Comment by schelhorn** [comment]
Yes, the problem Brad noticed likely isn't fixed, so I'd suggest that bcbio supports both binaries for now and allows the user to opt in for the parallel version. Then only people are affected who know what they're doing and are willing to help with bug reports.

**Comment by guillermo-carrasco** [comment]
Sounds good,

@schelhorn did you compile [this](https://github.com/nh13/samtools/tree/master/pbgzip) version of pbgzip? I am having troubles compiling it both in Mac (expected) and Linix. This is the last error in CentOS 6.6.  Do you recall having this issue?

```
...
gcc -g -Wall -O2 -pthread -o pbgzip ../bgzf.o ../knetfile.o util.o block.o consumer.o queue.o reader.o writer.o pbgzf.o pbgzip.o   -lm -lz -lbz2
consumer.o: In function `consumer_run':
consumer.c:(.text+0x3f3): undefined reference to `consumer_init_header'
consumer.c:(.text+0x47c): undefined reference to `consumer_update_header'
collect2: error: ld returned 1 exit status
...
```

I'll keep trying.

**Comment by nh13** [comment]
I was able to find an old commit with some *compiling* code and pushed it up here: https://github.com/nh13/pbgzip.  It is untested and I already found a bug (see https://github.com/nh13/pbgzip/issues/1).  Nonetheless, it should be a basis for seeing if we can get it working.

**Comment by guillermo-carrasco** [comment]
Nice, thanks! Let's then move the discussions in there.

**Comment by schelhorn** [comment]
Excellent, thanks for all the contributions. If no one objects I will close this issue in two days. We can reopen it once we have bug reports for samples where pbgzip failed.

**Comment by guillermo-carrasco** [comment]
Thanks @schelhorn , I've been compressing and uncompressing some samples without seeing any errors, I guess that some special race condition needs to happen.
